#-------------------------------
# Site Settings
title: Tiago Davies
logo: 
description: Portfolio page for Tiago Davies.
color_scheme: auto # Options: light, dark, auto

#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Projects'
      url: '/projects/'
    - title: 'Resume'
      url: '/Tiago-Resume.pdf'


#-------------------------------
# Author Settings
author:
  author__name: Tiago Davies
  author__bio: Like what you've seen? Click my links below!
  author__avatar: '/images/personal/Tiago-Portrait.jpg'

social:
- {icon: "ion-logo-linkedin", link: "https://www.linkedin.com/in/tiagodavies"}
- {icon: "ion-logo-github", link: "https://github.com/YAGOTAGO"}
- {icon: "ion-md-mail", link: "mailto:tiagocaetanodavies@gmail.com"}
- {icon: "ion-logo-game-controller-b", link: "https://tdavies.itch.io"}


#-------------------------------
# Hero Settings
hero:
  hero__title: Hi I'm Tiago.
  hero__description: | 
    I work as a <a href="#experience">Full-Stack Developer</a>, where I build web and mobile applications. 
    I studied at the University of Rochester where I earned a <b>B.S. in Computer Science</b>.
    <br><br>
    Outside of work I enjoy board games, cooking new recipes, and developing video games.
    <br><br>
    <a href="#projects">Check them out below!</a>
  hero__image: '/images/personal/Tiago-Portrait.jpg'

#-------------------------------
# Projects Settings
projects__settings:
  projects__title: Projects
  projects__description: 

#-------------------------------
# Footer Navigation Settings
footer_menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Projects'
      url: '/projects/'
    - title: 'Resume'
      url: '/Tiago-Resume.pdf'